### PR TITLE
update icon paths

### PR DESCRIPTION
**Pull request by Klumbumbus**
In JOSM we transformed png icons to svg ([JOSM ticket](https://josm.openstreetmap.de/ticket/13357)). This PR fixes the icon paths of this preset.

### CODE REVIEW

**Comment by chihchun** [comment]
LGTM. Thanks for the update the icons path.

However, the old png icons are removed from svn repository. This breaks the compatibility.

The current stable/testing release is svn r10786, which is still using the old icon path. I suggest wait for majority of users are upgraded to r10814 or newer , then we can merge this change.

**Comment by Klumbumbus** [comment]
Sorry for the noise, I was just testing github

**Comment by Klumbumbus** [comment]
Keeping the old icons wouldn't provide compatibility. With your preset you can support only josm-tested or josm-latest users. Your decision to support josm-tested users is ok. I will inform you when we release new tested version.

**Comment by Klumbumbus** [comment]
Next stable JOSM (10966 ) was released. It is now the best time to merge the PR.

**Comment by chihchun** [comment]
Thank you so much! Klumbumbus

**Comment by Klumbumbus** [comment]
thx

**Pull request merged**
